name: Security audit

on:
  schedule:
    # Runs at 00:00 on Monday
    - cron: '0 0 * * 1'
  workflow_dispatch:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
