name: Github Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  publish:
    name: Publish Book
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install mdBook
        run: |
          # Install mdBook
          mkdir -p ${{ runner.temp }}/bin/mdbook
          cd ${{ runner.temp }}/bin/mdbook
          wget 'https://github.com/rust-lang/mdBook/releases/download/v0.4.51/mdbook-v0.4.51-x86_64-unknown-linux-gnu.tar.gz' --output-document 'mdbook.tar.gz'
          tar -zxvf mdbook.tar.gz
          echo "${{ runner.temp }}/bin/mdbook" >> $GITHUB_PATH

      - name: Build Book
        run: mdbook build

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
