name: Build Template
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**/docs/**"
      - "**.md"

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      PROJECT_NAME: mytemplate
    steps:
      - uses: actions/checkout@v6

      - name: Install cargo generate
        run: |
          # Install cargo-generate
          mkdir -p ${{ runner.temp }}/bin/cargo-generate
          cd ${{ runner.temp }}/bin/cargo-generate
          wget 'https://github.com/cargo-generate/cargo-generate/releases/download/v0.23.8/cargo-generate-v0.23.8-x86_64-unknown-linux-gnu.tar.gz' --output-document 'cargo-generate.tar.gz'
          tar -zxvf cargo-generate.tar.gz
          echo "${{ runner.temp }}/bin/cargo-generate" >> $GITHUB_PATH

      - name: Generate
        run: |
          cargo-generate generate . --name ${{ env.PROJECT_NAME }} \
            -d gh-username="daxartio" \
            -d project-description="Example of Rust GitHub template" \
            -d license="MIT" \
            -d docs=true

      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable,nightly
          components: clippy,rustfmt

      - name: Cargo check
        run: |
          mv ${{ env.PROJECT_NAME }} ${{ runner.temp }}/
          cd ${{ runner.temp }}/${{ env.PROJECT_NAME }}
          cargo check
          cargo +nightly fmt --all -- --check
          cargo clippy --all-targets --all-features --workspace

      - name: Install mdBook
        run: |
          # Install mdBook
          mkdir -p ${{ runner.temp }}/bin/mdbook
          cd ${{ runner.temp }}/bin/mdbook
          wget 'https://github.com/rust-lang/mdBook/releases/download/v0.5.2/mdbook-v0.5.2-x86_64-unknown-linux-gnu.tar.gz' --output-document 'mdbook.tar.gz'
          tar -zxvf mdbook.tar.gz
          echo "${{ runner.temp }}/bin/mdbook" >> $GITHUB_PATH

      - name: Build Book
        run: |
          cd ${{ runner.temp }}/${{ env.PROJECT_NAME }}
          mdbook build
