name: Build Template
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**/docs/**"
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      PROJECT_NAME: mytemplate
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo generate
        run: |
          wget 'https://github.com/cargo-generate/cargo-generate/releases/download/v0.22.0/cargo-generate-v0.22.0-x86_64-unknown-linux-gnu.tar.gz' --output-document 'cargo-generate.tar.gz'
          tar -zxvf cargo-generate.tar.gz
      - name: Generate
        run: |
          ./cargo-generate generate . --name ${{ env.PROJECT_NAME }} \
            -d gh-username="daxartio" \
            -d project-description="Example of Rust GitHub template" \
            -d license="MIT" \
            -d docs=true
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cargo check
        run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          cargo check
